"""add_document_models_and_icd10

Revision ID: 6ea4c9de08ce
Revises: f597d1d4d9b3
Create Date: 2026-02-14 19:29:00.401602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ea4c9de08ce'
down_revision: Union[str, Sequence[str], None] = 'f597d1d4d9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.String(length=50), nullable=True),
    sa.Column('provider_name', sa.String(length=255), nullable=True),
    sa.Column('facility_name', sa.String(length=500), nullable=True),
    sa.Column('parse_status', sa.String(length=50), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('raw_parse_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['health_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follow_ups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timeframe', sa.String(length=100), nullable=True),
    sa.Column('target_date', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['health_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('ordered_date', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['health_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('specialty', sa.String(length=255), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['health_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vitals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('weight', sa.String(length=50), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('blood_pressure', sa.String(length=20), nullable=True),
    sa.Column('heart_rate', sa.String(length=20), nullable=True),
    sa.Column('temperature', sa.String(length=20), nullable=True),
    sa.Column('measured_date', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['health_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.add_column('conditions', sa.Column('icd_10', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conditions', 'icd_10')
    op.drop_table('vitals')
    op.drop_table('referrals')
    op.drop_table('lab_orders')
    op.drop_table('follow_ups')
    op.drop_table('documents')
    # ### end Alembic commands ###
