"""Add snooze completion state to action items

Revision ID: 956a4ae83ec1
Revises: 6ea4c9de08ce
Create Date: 2026-07-05 16:45:56.839123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '956a4ae83ec1'
down_revision: Union[str, Sequence[str], None] = '6ea4c9de08ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nudge_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('nudge_type', sa.String(length=100), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('snoozed_until', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['health_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('follow_ups', sa.Column('snoozed_until', sa.DateTime(), nullable=True))
    op.add_column('follow_ups', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('lab_orders', sa.Column('snoozed_until', sa.DateTime(), nullable=True))
    op.add_column('lab_orders', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('referrals', sa.Column('snoozed_until', sa.DateTime(), nullable=True))
    op.add_column('referrals', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referrals', 'completed_at')
    op.drop_column('referrals', 'snoozed_until')
    op.drop_column('lab_orders', 'completed_at')
    op.drop_column('lab_orders', 'snoozed_until')
    op.drop_column('follow_ups', 'completed_at')
    op.drop_column('follow_ups', 'snoozed_until')
    op.drop_table('nudge_states')
    # ### end Alembic commands ###
